// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/main.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Direction int32

const (
	Direction_UP    Direction = 0
	Direction_DOWN  Direction = 1
	Direction_LEFT  Direction = 2
	Direction_RIGHT Direction = 3
	Direction_STOP  Direction = 4
)

var Direction_name = map[int32]string{
	0: "UP",
	1: "DOWN",
	2: "LEFT",
	3: "RIGHT",
	4: "STOP",
}

var Direction_value = map[string]int32{
	"UP":    0,
	"DOWN":  1,
	"LEFT":  2,
	"RIGHT": 3,
	"STOP":  4,
}

func (x Direction) String() string {
	return proto.EnumName(Direction_name, int32(x))
}

func (Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{0}
}

type Coordinate struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{0}
}

func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (m *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(m, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Coordinate) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Player struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position             *Coordinate `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{1}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetPosition() *Coordinate {
	if m != nil {
		return m.Position
	}
	return nil
}

type Laser struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Direction            Direction            `protobuf:"varint,2,opt,name=direction,proto3,enum=proto.Direction" json:"direction,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	InitialPosition      *Coordinate          `protobuf:"bytes,4,opt,name=initialPosition,proto3" json:"initialPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Laser) Reset()         { *m = Laser{} }
func (m *Laser) String() string { return proto.CompactTextString(m) }
func (*Laser) ProtoMessage()    {}
func (*Laser) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{2}
}

func (m *Laser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Laser.Unmarshal(m, b)
}
func (m *Laser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Laser.Marshal(b, m, deterministic)
}
func (m *Laser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Laser.Merge(m, src)
}
func (m *Laser) XXX_Size() int {
	return xxx_messageInfo_Laser.Size(m)
}
func (m *Laser) XXX_DiscardUnknown() {
	xxx_messageInfo_Laser.DiscardUnknown(m)
}

var xxx_messageInfo_Laser proto.InternalMessageInfo

func (m *Laser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Laser) GetDirection() Direction {
	if m != nil {
		return m.Direction
	}
	return Direction_UP
}

func (m *Laser) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Laser) GetInitialPosition() *Coordinate {
	if m != nil {
		return m.InitialPosition
	}
	return nil
}

type Entity struct {
	// Types that are valid to be assigned to Entity:
	//	*Entity_Player
	//	*Entity_Laser
	Entity               isEntity_Entity `protobuf_oneof:"entity"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{3}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

type isEntity_Entity interface {
	isEntity_Entity()
}

type Entity_Player struct {
	Player *Player `protobuf:"bytes,2,opt,name=player,proto3,oneof"`
}

type Entity_Laser struct {
	Laser *Laser `protobuf:"bytes,3,opt,name=laser,proto3,oneof"`
}

func (*Entity_Player) isEntity_Entity() {}

func (*Entity_Laser) isEntity_Entity() {}

func (m *Entity) GetEntity() isEntity_Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *Entity) GetPlayer() *Player {
	if x, ok := m.GetEntity().(*Entity_Player); ok {
		return x.Player
	}
	return nil
}

func (m *Entity) GetLaser() *Laser {
	if x, ok := m.GetEntity().(*Entity_Laser); ok {
		return x.Laser
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Entity) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Entity_Player)(nil),
		(*Entity_Laser)(nil),
	}
}

type Connect struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connect) Reset()         { *m = Connect{} }
func (m *Connect) String() string { return proto.CompactTextString(m) }
func (*Connect) ProtoMessage()    {}
func (*Connect) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{4}
}

func (m *Connect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connect.Unmarshal(m, b)
}
func (m *Connect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connect.Marshal(b, m, deterministic)
}
func (m *Connect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connect.Merge(m, src)
}
func (m *Connect) XXX_Size() int {
	return xxx_messageInfo_Connect.Size(m)
}
func (m *Connect) XXX_DiscardUnknown() {
	xxx_messageInfo_Connect.DiscardUnknown(m)
}

var xxx_messageInfo_Connect proto.InternalMessageInfo

func (m *Connect) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Connect) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Initialize struct {
	Position             *Coordinate `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Entities             []*Entity   `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Initialize) Reset()         { *m = Initialize{} }
func (m *Initialize) String() string { return proto.CompactTextString(m) }
func (*Initialize) ProtoMessage()    {}
func (*Initialize) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{5}
}

func (m *Initialize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Initialize.Unmarshal(m, b)
}
func (m *Initialize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Initialize.Marshal(b, m, deterministic)
}
func (m *Initialize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Initialize.Merge(m, src)
}
func (m *Initialize) XXX_Size() int {
	return xxx_messageInfo_Initialize.Size(m)
}
func (m *Initialize) XXX_DiscardUnknown() {
	xxx_messageInfo_Initialize.DiscardUnknown(m)
}

var xxx_messageInfo_Initialize proto.InternalMessageInfo

func (m *Initialize) GetPosition() *Coordinate {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Initialize) GetEntities() []*Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

type Move struct {
	Direction            Direction `protobuf:"varint,1,opt,name=direction,proto3,enum=proto.Direction" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Move) Reset()         { *m = Move{} }
func (m *Move) String() string { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()    {}
func (*Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{6}
}

func (m *Move) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Move.Unmarshal(m, b)
}
func (m *Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Move.Marshal(b, m, deterministic)
}
func (m *Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Move.Merge(m, src)
}
func (m *Move) XXX_Size() int {
	return xxx_messageInfo_Move.Size(m)
}
func (m *Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Move proto.InternalMessageInfo

func (m *Move) GetDirection() Direction {
	if m != nil {
		return m.Direction
	}
	return Direction_UP
}

type AddEntity struct {
	Entity               *Entity  `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEntity) Reset()         { *m = AddEntity{} }
func (m *AddEntity) String() string { return proto.CompactTextString(m) }
func (*AddEntity) ProtoMessage()    {}
func (*AddEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{7}
}

func (m *AddEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEntity.Unmarshal(m, b)
}
func (m *AddEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEntity.Marshal(b, m, deterministic)
}
func (m *AddEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEntity.Merge(m, src)
}
func (m *AddEntity) XXX_Size() int {
	return xxx_messageInfo_AddEntity.Size(m)
}
func (m *AddEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEntity.DiscardUnknown(m)
}

var xxx_messageInfo_AddEntity proto.InternalMessageInfo

func (m *AddEntity) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type UpdateEntity struct {
	Entity               *Entity  `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEntity) Reset()         { *m = UpdateEntity{} }
func (m *UpdateEntity) String() string { return proto.CompactTextString(m) }
func (*UpdateEntity) ProtoMessage()    {}
func (*UpdateEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{8}
}

func (m *UpdateEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEntity.Unmarshal(m, b)
}
func (m *UpdateEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEntity.Marshal(b, m, deterministic)
}
func (m *UpdateEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEntity.Merge(m, src)
}
func (m *UpdateEntity) XXX_Size() int {
	return xxx_messageInfo_UpdateEntity.Size(m)
}
func (m *UpdateEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEntity.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEntity proto.InternalMessageInfo

func (m *UpdateEntity) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type RemoveEntity struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveEntity) Reset()         { *m = RemoveEntity{} }
func (m *RemoveEntity) String() string { return proto.CompactTextString(m) }
func (*RemoveEntity) ProtoMessage()    {}
func (*RemoveEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{9}
}

func (m *RemoveEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveEntity.Unmarshal(m, b)
}
func (m *RemoveEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveEntity.Marshal(b, m, deterministic)
}
func (m *RemoveEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveEntity.Merge(m, src)
}
func (m *RemoveEntity) XXX_Size() int {
	return xxx_messageInfo_RemoveEntity.Size(m)
}
func (m *RemoveEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveEntity.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveEntity proto.InternalMessageInfo

type PlayerKilled struct {
	SpawnPosition        *Coordinate `protobuf:"bytes,1,opt,name=spawnPosition,proto3" json:"spawnPosition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlayerKilled) Reset()         { *m = PlayerKilled{} }
func (m *PlayerKilled) String() string { return proto.CompactTextString(m) }
func (*PlayerKilled) ProtoMessage()    {}
func (*PlayerKilled) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{10}
}

func (m *PlayerKilled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerKilled.Unmarshal(m, b)
}
func (m *PlayerKilled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerKilled.Marshal(b, m, deterministic)
}
func (m *PlayerKilled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerKilled.Merge(m, src)
}
func (m *PlayerKilled) XXX_Size() int {
	return xxx_messageInfo_PlayerKilled.Size(m)
}
func (m *PlayerKilled) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerKilled.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerKilled proto.InternalMessageInfo

func (m *PlayerKilled) GetSpawnPosition() *Coordinate {
	if m != nil {
		return m.SpawnPosition
	}
	return nil
}

type Request struct {
	// Types that are valid to be assigned to Action:
	//	*Request_Connect
	//	*Request_Move
	//	*Request_Laser
	Action               isRequest_Action `protobuf_oneof:"action"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{11}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type isRequest_Action interface {
	isRequest_Action()
}

type Request_Connect struct {
	Connect *Connect `protobuf:"bytes,1,opt,name=connect,proto3,oneof"`
}

type Request_Move struct {
	Move *Move `protobuf:"bytes,2,opt,name=move,proto3,oneof"`
}

type Request_Laser struct {
	Laser *Laser `protobuf:"bytes,3,opt,name=laser,proto3,oneof"`
}

func (*Request_Connect) isRequest_Action() {}

func (*Request_Move) isRequest_Action() {}

func (*Request_Laser) isRequest_Action() {}

func (m *Request) GetAction() isRequest_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *Request) GetConnect() *Connect {
	if x, ok := m.GetAction().(*Request_Connect); ok {
		return x.Connect
	}
	return nil
}

func (m *Request) GetMove() *Move {
	if x, ok := m.GetAction().(*Request_Move); ok {
		return x.Move
	}
	return nil
}

func (m *Request) GetLaser() *Laser {
	if x, ok := m.GetAction().(*Request_Laser); ok {
		return x.Laser
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Request) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Request_Connect)(nil),
		(*Request_Move)(nil),
		(*Request_Laser)(nil),
	}
}

type Response struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Action:
	//	*Response_Initialize
	//	*Response_AddEntity
	//	*Response_UpdateEntity
	//	*Response_RemoveEntity
	//	*Response_PlayerKilled
	Action               isResponse_Action `protobuf_oneof:"action"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_098391ad7281b52b, []int{12}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type isResponse_Action interface {
	isResponse_Action()
}

type Response_Initialize struct {
	Initialize *Initialize `protobuf:"bytes,2,opt,name=initialize,proto3,oneof"`
}

type Response_AddEntity struct {
	AddEntity *AddEntity `protobuf:"bytes,3,opt,name=addEntity,proto3,oneof"`
}

type Response_UpdateEntity struct {
	UpdateEntity *UpdateEntity `protobuf:"bytes,4,opt,name=updateEntity,proto3,oneof"`
}

type Response_RemoveEntity struct {
	RemoveEntity *RemoveEntity `protobuf:"bytes,5,opt,name=removeEntity,proto3,oneof"`
}

type Response_PlayerKilled struct {
	PlayerKilled *PlayerKilled `protobuf:"bytes,6,opt,name=playerKilled,proto3,oneof"`
}

func (*Response_Initialize) isResponse_Action() {}

func (*Response_AddEntity) isResponse_Action() {}

func (*Response_UpdateEntity) isResponse_Action() {}

func (*Response_RemoveEntity) isResponse_Action() {}

func (*Response_PlayerKilled) isResponse_Action() {}

func (m *Response) GetAction() isResponse_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *Response) GetInitialize() *Initialize {
	if x, ok := m.GetAction().(*Response_Initialize); ok {
		return x.Initialize
	}
	return nil
}

func (m *Response) GetAddEntity() *AddEntity {
	if x, ok := m.GetAction().(*Response_AddEntity); ok {
		return x.AddEntity
	}
	return nil
}

func (m *Response) GetUpdateEntity() *UpdateEntity {
	if x, ok := m.GetAction().(*Response_UpdateEntity); ok {
		return x.UpdateEntity
	}
	return nil
}

func (m *Response) GetRemoveEntity() *RemoveEntity {
	if x, ok := m.GetAction().(*Response_RemoveEntity); ok {
		return x.RemoveEntity
	}
	return nil
}

func (m *Response) GetPlayerKilled() *PlayerKilled {
	if x, ok := m.GetAction().(*Response_PlayerKilled); ok {
		return x.PlayerKilled
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_Initialize)(nil),
		(*Response_AddEntity)(nil),
		(*Response_UpdateEntity)(nil),
		(*Response_RemoveEntity)(nil),
		(*Response_PlayerKilled)(nil),
	}
}

func init() {
	proto.RegisterEnum("proto.Direction", Direction_name, Direction_value)
	proto.RegisterType((*Coordinate)(nil), "proto.Coordinate")
	proto.RegisterType((*Player)(nil), "proto.Player")
	proto.RegisterType((*Laser)(nil), "proto.Laser")
	proto.RegisterType((*Entity)(nil), "proto.Entity")
	proto.RegisterType((*Connect)(nil), "proto.Connect")
	proto.RegisterType((*Initialize)(nil), "proto.Initialize")
	proto.RegisterType((*Move)(nil), "proto.Move")
	proto.RegisterType((*AddEntity)(nil), "proto.AddEntity")
	proto.RegisterType((*UpdateEntity)(nil), "proto.UpdateEntity")
	proto.RegisterType((*RemoveEntity)(nil), "proto.RemoveEntity")
	proto.RegisterType((*PlayerKilled)(nil), "proto.PlayerKilled")
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() {
	proto.RegisterFile("proto/main.proto", fileDescriptor_098391ad7281b52b)
}

var fileDescriptor_098391ad7281b52b = []byte{
	// 636 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5f, 0x53, 0xd3, 0x4e,
	0x14, 0x4d, 0x42, 0x1a, 0x9a, 0x4b, 0x29, 0xf9, 0xed, 0xef, 0xa5, 0xc3, 0x8b, 0x98, 0xd1, 0xb1,
	0x32, 0x43, 0xcb, 0x94, 0x51, 0x74, 0xf4, 0x45, 0x01, 0x09, 0x23, 0x4a, 0x67, 0x29, 0xe3, 0x83,
	0x4f, 0x0b, 0x59, 0x98, 0x9d, 0x69, 0xb2, 0x31, 0x59, 0x90, 0xfa, 0x09, 0xfc, 0x50, 0x8e, 0x9f,
	0xcd, 0xd9, 0x3f, 0x49, 0x13, 0xd4, 0x29, 0x3e, 0x75, 0xff, 0x9c, 0xb3, 0xf7, 0xdc, 0x73, 0x6e,
	0x03, 0x41, 0x96, 0x73, 0xc1, 0x87, 0x09, 0x61, 0xe9, 0x40, 0x2d, 0x51, 0x4b, 0xfd, 0xac, 0x3f,
	0xb8, 0xe2, 0xfc, 0x6a, 0x4a, 0x87, 0x6a, 0x77, 0x7e, 0x7d, 0x39, 0x14, 0x2c, 0xa1, 0x85, 0x20,
	0x49, 0xa6, 0x71, 0x61, 0x1f, 0x60, 0x8f, 0xf3, 0x3c, 0x66, 0x29, 0x11, 0x14, 0x75, 0xc0, 0xbe,
	0xed, 0xd9, 0x1b, 0x76, 0xbf, 0x85, 0xed, 0x5b, 0xb9, 0x9b, 0xf5, 0x1c, 0xbd, 0x9b, 0x85, 0x9f,
	0xc1, 0x1b, 0x4f, 0xc9, 0x8c, 0xe6, 0xa8, 0x0b, 0x0e, 0x8b, 0x15, 0xcc, 0xc7, 0x0e, 0x8b, 0x11,
	0x02, 0x37, 0x25, 0x09, 0x55, 0x50, 0x1f, 0xab, 0x35, 0xda, 0x82, 0x76, 0xc6, 0x0b, 0x26, 0x18,
	0x4f, 0x7b, 0x4b, 0x1b, 0x76, 0x7f, 0x65, 0xf4, 0x9f, 0xae, 0x38, 0x98, 0x97, 0xc3, 0x15, 0x24,
	0xfc, 0x69, 0x43, 0xeb, 0x98, 0x14, 0x7f, 0x78, 0x7c, 0x00, 0x7e, 0xcc, 0x72, 0x7a, 0xa1, 0x5e,
	0x92, 0x15, 0xba, 0xa3, 0xc0, 0xbc, 0xb4, 0x5f, 0x9e, 0xe3, 0x39, 0x04, 0xbd, 0x00, 0xbf, 0x10,
	0x24, 0x17, 0x13, 0x96, 0x50, 0x53, 0x79, 0x7d, 0xa0, 0x5d, 0x18, 0x94, 0x2e, 0x0c, 0x26, 0xa5,
	0x0b, 0x78, 0x0e, 0x46, 0xaf, 0x60, 0x8d, 0xa5, 0x4c, 0x30, 0x32, 0x1d, 0x97, 0xca, 0xdd, 0xbf,
	0x29, 0xbf, 0x8b, 0x0c, 0x09, 0x78, 0x07, 0xa9, 0x60, 0x62, 0x86, 0x9e, 0x80, 0x97, 0x29, 0x9f,
	0x94, 0xda, 0x95, 0xd1, 0xaa, 0x61, 0x6b, 0xf3, 0x22, 0x0b, 0x9b, 0x6b, 0xf4, 0x08, 0x5a, 0x53,
	0xd9, 0xb2, 0x51, 0xd9, 0x31, 0x38, 0x65, 0x43, 0x64, 0x61, 0x7d, 0xf9, 0xb6, 0x0d, 0x1e, 0x55,
	0x0f, 0x87, 0x5b, 0xb0, 0xbc, 0xc7, 0xd3, 0x94, 0x5e, 0x88, 0xfb, 0x24, 0x10, 0x5e, 0x02, 0x1c,
	0x69, 0x91, 0xec, 0x5b, 0x33, 0x0f, 0x7b, 0x61, 0x1e, 0xe8, 0x29, 0xb4, 0x55, 0x55, 0x46, 0x8b,
	0x9e, 0xb3, 0xb1, 0x54, 0x6b, 0x43, 0x77, 0x89, 0xab, 0xeb, 0xf0, 0x39, 0xb8, 0x1f, 0xf8, 0x0d,
	0x6d, 0x06, 0x65, 0x2f, 0x0c, 0x2a, 0x1c, 0x81, 0xff, 0x26, 0x8e, 0x8d, 0x69, 0x8f, 0xcb, 0x2e,
	0x8d, 0xb8, 0x3b, 0xd5, 0x4a, 0x0b, 0x9e, 0x41, 0xe7, 0x2c, 0x8b, 0x89, 0xa0, 0xff, 0x46, 0xeb,
	0x42, 0x07, 0xd3, 0x84, 0xdf, 0x18, 0x5a, 0x78, 0x08, 0x1d, 0x9d, 0xc6, 0x7b, 0x36, 0x9d, 0xd2,
	0x18, 0xed, 0xc2, 0x6a, 0x91, 0x91, 0xaf, 0xe9, 0x78, 0xa1, 0x43, 0x4d, 0x5c, 0xf8, 0xdd, 0x86,
	0x65, 0x4c, 0xbf, 0x5c, 0xd3, 0x42, 0xa0, 0x4d, 0x58, 0xbe, 0xd0, 0xf1, 0x18, 0x7a, 0xb7, 0xa2,
	0xab, 0xd3, 0xc8, 0xc2, 0x25, 0x00, 0x3d, 0x04, 0x57, 0xca, 0x31, 0x13, 0xb2, 0x62, 0x80, 0xd2,
	0xc6, 0xc8, 0xc2, 0xea, 0xea, 0xfe, 0xd3, 0x41, 0xb4, 0x9d, 0x3f, 0x1c, 0x68, 0x63, 0x5a, 0x64,
	0x3c, 0x2d, 0xe8, 0x6f, 0xf3, 0xb1, 0x03, 0xc0, 0xaa, 0x59, 0x30, 0x55, 0xcb, 0xee, 0xe6, 0x43,
	0x12, 0x59, 0xb8, 0x06, 0x43, 0xdb, 0xe0, 0x93, 0x32, 0x20, 0xa3, 0xa2, 0x0c, 0xb4, 0x0a, 0x2e,
	0xb2, 0xf0, 0x1c, 0x84, 0x5e, 0x42, 0xe7, 0xba, 0x16, 0x8f, 0xf9, 0xfb, 0xfc, 0x6f, 0x48, 0xf5,
	0xe4, 0x22, 0x0b, 0x37, 0xa0, 0x92, 0x9a, 0xd7, 0x22, 0xea, 0xb5, 0x1a, 0xd4, 0x7a, 0x7a, 0x92,
	0x5a, 0x87, 0x4a, 0x6a, 0x56, 0x4b, 0xb3, 0xe7, 0x35, 0xa8, 0xf5, 0xa0, 0x25, 0xb5, 0x0e, 0x9d,
	0xdb, 0xb7, 0xf9, 0x1a, 0xfc, 0x6a, 0x4a, 0x91, 0x07, 0xce, 0xd9, 0x38, 0xb0, 0x50, 0x1b, 0xdc,
	0xfd, 0x93, 0x4f, 0x1f, 0x03, 0x5b, 0xae, 0x8e, 0x0f, 0xde, 0x4d, 0x02, 0x07, 0xf9, 0xd0, 0xc2,
	0x47, 0x87, 0xd1, 0x24, 0x58, 0x92, 0x87, 0xa7, 0x93, 0x93, 0x71, 0xe0, 0x8e, 0x76, 0xc1, 0x3d,
	0x94, 0x5f, 0xbd, 0x21, 0x78, 0xa7, 0x22, 0xa7, 0x24, 0x41, 0xdd, 0x4a, 0xb9, 0x9a, 0x8e, 0xf5,
	0xb5, 0x6a, 0xaf, 0x23, 0x0a, 0xad, 0xbe, 0xbd, 0x6d, 0x9f, 0x7b, 0xea, 0x74, 0xe7, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xa9, 0x8f, 0x6c, 0x8b, 0xc1, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (Game_StreamClient, error)
}

type gameClient struct {
	cc grpc.ClientConnInterface
}

func NewGameClient(cc grpc.ClientConnInterface) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Game_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Game_serviceDesc.Streams[0], "/proto.Game/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameStreamClient{stream}
	return x, nil
}

type Game_StreamClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type gameStreamClient struct {
	grpc.ClientStream
}

func (x *gameStreamClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameStreamClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameServer is the server API for Game service.
type GameServer interface {
	Stream(Game_StreamServer) error
}

// UnimplementedGameServer can be embedded to have forward compatible implementations.
type UnimplementedGameServer struct {
}

func (*UnimplementedGameServer) Stream(srv Game_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

func RegisterGameServer(s *grpc.Server, srv GameServer) {
	s.RegisterService(&_Game_serviceDesc, srv)
}

func _Game_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServer).Stream(&gameStreamServer{stream})
}

type Game_StreamServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type gameStreamServer struct {
	grpc.ServerStream
}

func (x *gameStreamServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameStreamServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Game_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Game",
	HandlerType: (*GameServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Game_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/main.proto",
}
